minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - fastq@1.20.3
  - zod@4.5.2
  - zod@4.5.4
patchedDependencies:
  '@mediapipe/tasks-vision@1.0.1': patches/@mediapipe__tasks-vision@1.0.1.patch
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
